### ISSUE TITLE
Schema editor: Cannot create classes with properties where input is expected to be of class being created

### ISSUE THREAD

**Issue by gtsueng** [biothings/discovery-app#82]
In trying to re-create the [bioschemas:Taxon class](https://bioschemas.org/types/Taxon/0.3-RELEASE-2019_11_18/), the [schema editor-created class](https://github.com/gtsueng/DDE_bioschemas/blob/main/bioschemastest_Taxon.jsonld) will not load in the schema playground viewer, instead giving an internal server error. Quick glance at the log suggests circular referencing to be a problem.  Furthermore, removal of the circular reference type, [allows it to work](https://github.com/gtsueng/DDE_bioschemas/blob/main/bioschemastest_Taxon_test_2.jsonld).

This is probably due to the property `parentTaxon` where the expected value is `Taxon` the class that is being created.  This kind of circular referencing is required for a number of bioschemas, so someway around this issue is desirable.

**Comment by marcodarko** [comment]
`Traceback (most recent call last):
      File "/Users/marco/Desktop/code/discovery-app/env/lib/python3.8/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/Users/marco/Desktop/code/discovery-app/env/lib/python3.8/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/marco/Desktop/code/discovery-app/discovery/web/api/schema.py", line 368, in get
        self.finish(response)
      File "/Users/marco/Desktop/code/discovery-app/env/lib/python3.8/site-packages/tornado/web.py", line 1025, in finish
        self.write(chunk)
      File "/Users/marco/Desktop/code/discovery-app/env/lib/python3.8/site-packages/biothings/web/handlers/api.py", line 152, in write
        chunk = json.dumps(chunk, cls=DateTimeJSONEncoder)
      File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
        return cls(
      File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
        return _iterencode(o, 0)
    ValueError: Circular reference detected`

Adding the error for ref.

**Comment by marcodarko** [comment]
Issue is created when a class includes **validation** but that validation is empty or only includes a `description` but no validation rules.  The schema package has a bug that duplicates the `$schema`` type` and `properties` under each property thus creating the **Circular reference**

**Comment by gtsueng** [comment]
Work around is to always create a validation. Issue with work around is that some classes are intentionally broad/unused to serve as a basis for other classes, and would not expect to ever require data validation. Eg- BioSchemas:BiochemicalEntity is base class for BioSchemas:Protein, and we would expect to create validation for Protein data, but not for BiochemicalEntity.
